sudo: required
services: 
  - docker

before_install:
  - docker build -t bmvinay113/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true bmvinay113/docker-react npm run test -- --coverage